# ============================================
# GestaoVersus - Google Cloud App Engine
# ============================================
# Configuração para deploy no App Engine
# ============================================

runtime: python39

# Configuração de instâncias
instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

# Entrypoint
entrypoint: gunicorn -b :$PORT app_pev:app --workers 2 --threads 2 --timeout 120

# Variáveis de ambiente (use Secret Manager em produção!)
env_variables:
  FLASK_ENV: "production"
  PYTHON_VERSION: "3.9"

# Health check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Manipuladores de arquivos
handlers:
  # Static files
  - url: /static
    static_dir: static
    secure: always
    redirect_http_response_code: 301
  
  # Uploads (não recomendado em App Engine - usar Cloud Storage)
  - url: /uploads
    static_dir: uploads
    secure: always
    redirect_http_response_code: 301
  
  # Todas as outras rotas
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# VPC Connector (se usar Cloud SQL)
vpc_access_connector:
  name: "projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME"

# ⚠️ IMPORTANTE:
# 1. Substitua PROJECT_ID, REGION, CONNECTOR_NAME
# 2. Use Secret Manager para variáveis sensíveis
# 3. Configure Cloud SQL Proxy para banco de dados
# 4. Use Cloud Storage para uploads
