# Google Cloud Run Service Configuration
# GestaoVersus (APP30)

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gestaoversos-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Scaling
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        
        # VPC Connector
        run.googleapis.com/vpc-access-connector: gestaoversos-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        
        # Cloud SQL
        run.googleapis.com/cloudsql-instances: PROJECT_ID:us-central1:gestaoversos-db
        
        # Resources
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: gestaoversos-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
        - image: gcr.io/PROJECT_ID/gestaoversos-app:latest
          
          ports:
            - name: http1
              containerPort: 5002
          
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
          
          env:
            - name: FLASK_ENV
              value: production
            
            - name: PORT
              value: '5002'
            
            - name: APP_NAME
              value: GestaoVersus
            
            - name: DOMAIN
              value: your-domain.com
            
            # Secrets (via Secret Manager)
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: SECRET_KEY
                  key: latest
            
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: DATABASE_URL
                  key: latest
            
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: OPENAI_API_KEY
                  key: latest
            
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: MAIL_USERNAME
                  key: latest
            
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: MAIL_PASSWORD
                  key: latest
            
            - name: WHATSAPP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: WHATSAPP_API_KEY
                  key: latest
          
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          
          startupProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
  
  traffic:
    - percent: 100
      latestRevision: true


