# ============================================
# GestaoVersus - Google Cloud Build
# ============================================
# CI/CD automático com Cloud Build
# ============================================

steps:
  # ==========================================
  # Step 1: Run Tests
  # ==========================================
  - name: 'python:3.9-slim'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install pytest pytest-flask
        pytest || exit 1

  # ==========================================
  # Step 2: Build Docker Image
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:$COMMIT_SHA'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # ==========================================
  # Step 3: Push to Artifact Registry
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:latest'

  # ==========================================
  # Step 4: Deploy to Cloud Run
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gestaoversos'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'FLASK_ENV=production'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'

  # ==========================================
  # Step 5: Run Database Migrations
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'migrate'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs execute db-migration \
          --region southamerica-east1 \
          --wait || echo "Migration job not found, skipping"

  # ==========================================
  # Step 6: Health Check
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$$(gcloud run services describe gestaoversos --region southamerica-east1 --format 'value(status.url)')
        echo "Testing: $$SERVICE_URL/health"
        curl -f $$SERVICE_URL/health || exit 1
        echo "✅ Health check passed!"

# ==========================================
# Images to push
# ==========================================
images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:$COMMIT_SHA'
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-backend:latest'

# ==========================================
# Options
# ==========================================
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1800s'  # 30 minutos

# ==========================================
# Substitutions
# ==========================================
substitutions:
  _REGION: 'southamerica-east1'
  _SERVICE_NAME: 'gestaoversos'

# ==========================================
# Trigger Configuration (via Console ou gcloud)
# ==========================================
# Trigger on push to 'main' branch:
# gcloud builds triggers create github \
#   --repo-name=Principal \
#   --repo-owner=VrsEco \
#   --branch-pattern="^main$" \
#   --build-config=cloudbuild.yaml \
#   --region=southamerica-east1
