#!/usr/bin/env python3
"""
Integration Configuration Script for PEVAPP22
This script helps configure AI, Email, and WhatsApp integrations
"""

import os
import json
from pathlib import Path

class IntegrationConfigurator:
    """Configure integrations for PEVAPP22"""
    
    def __init__(self):
        self.env_file = Path('.env')
        self.config = {}
        self.load_current_config()
    
    def load_current_config(self):
        """Load current configuration from .env file"""
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        self.config[key] = value
    
    def save_config(self):
        """Save configuration to .env file"""
        with open(self.env_file, 'w') as f:
            f.write("# PEVAPP22 Configuration\n")
            f.write("# Generated by configure_integrations.py\n\n")
            
            # Database
            f.write("# Database\n")
            f.write(f"DATABASE_URL={self.config.get('DATABASE_URL', 'sqlite:///pevapp22.db')}\n")
            f.write(f"DEV_DATABASE_URL={self.config.get('DEV_DATABASE_URL', 'sqlite:///pevapp22_dev.db')}\n\n")
            
            # Security
            f.write("# Security\n")
            f.write(f"SECRET_KEY={self.config.get('SECRET_KEY', 'dev-secret-key-change-in-production')}\n")
            f.write(f"LOGIN_DISABLED={self.config.get('LOGIN_DISABLED', 'False')}\n\n")
            
            # Email
            f.write("# Email Configuration\n")
            f.write(f"MAIL_SERVER={self.config.get('MAIL_SERVER', '')}\n")
            f.write(f"MAIL_PORT={self.config.get('MAIL_PORT', '587')}\n")
            f.write(f"MAIL_USE_TLS={self.config.get('MAIL_USE_TLS', 'True')}\n")
            f.write(f"MAIL_USERNAME={self.config.get('MAIL_USERNAME', '')}\n")
            f.write(f"MAIL_PASSWORD={self.config.get('MAIL_PASSWORD', '')}\n")
            f.write(f"MAIL_DEFAULT_SENDER={self.config.get('MAIL_DEFAULT_SENDER', '')}\n\n")
            
            # AI Integration
            f.write("# AI Integration\n")
            f.write(f"AI_PROVIDER={self.config.get('AI_PROVIDER', 'openai')}\n")
            f.write(f"AI_API_KEY={self.config.get('AI_API_KEY', '')}\n")
            f.write(f"AI_WEBHOOK_URL={self.config.get('AI_WEBHOOK_URL', '')}\n\n")
            
            # WhatsApp Integration
            f.write("# WhatsApp Integration\n")
            f.write(f"WHATSAPP_PROVIDER={self.config.get('WHATSAPP_PROVIDER', 'z-api')}\n")
            f.write(f"WHATSAPP_API_KEY={self.config.get('WHATSAPP_API_KEY', '')}\n")
            f.write(f"WHATSAPP_WEBHOOK_URL={self.config.get('WHATSAPP_WEBHOOK_URL', '')}\n")
            f.write(f"WHATSAPP_INSTANCE_ID={self.config.get('WHATSAPP_INSTANCE_ID', '')}\n\n")
            
            # Redis
            f.write("# Redis\n")
            f.write(f"REDIS_URL={self.config.get('REDIS_URL', 'redis://localhost:6379/0')}\n\n")
            
            # Environment
            f.write("# Environment\n")
            f.write(f"FLASK_ENV={self.config.get('FLASK_ENV', 'development')}\n")
    
    def configure_ai(self):
        """Configure AI integration"""
        print("\n🤖 AI Integration Configuration")
        print("=" * 40)
        
        print("Available AI providers:")
        print("1. OpenAI (GPT-3.5/GPT-4)")
        print("2. Anthropic (Claude)")
        print("3. Webhook (Custom)")
        print("4. Local (Basic analysis)")
        
        choice = input("\nSelect AI provider (1-4): ").strip()
        
        if choice == '1':
            self.config['AI_PROVIDER'] = 'openai'
            api_key = input("Enter OpenAI API key: ").strip()
            if api_key:
                self.config['AI_API_KEY'] = api_key
                print("✅ OpenAI configured")
            else:
                print("❌ OpenAI API key required")
        
        elif choice == '2':
            self.config['AI_PROVIDER'] = 'anthropic'
            api_key = input("Enter Anthropic API key: ").strip()
            if api_key:
                self.config['AI_API_KEY'] = api_key
                print("✅ Anthropic configured")
            else:
                print("❌ Anthropic API key required")
        
        elif choice == '3':
            self.config['AI_PROVIDER'] = 'webhook'
            webhook_url = input("Enter webhook URL: ").strip()
            if webhook_url:
                self.config['AI_WEBHOOK_URL'] = webhook_url
                print("✅ Webhook configured")
            else:
                print("❌ Webhook URL required")
        
        elif choice == '4':
            self.config['AI_PROVIDER'] = 'local'
            print("✅ Local AI analysis configured")
        
        else:
            print("❌ Invalid choice")
    
    def configure_email(self):
        """Configure email integration"""
        print("\n📧 Email Configuration")
        print("=" * 40)
        
        print("Available email providers:")
        print("1. SMTP (Gmail, Outlook, etc.)")
        print("2. Webhook (Custom)")
        print("3. Local (Simulation)")
        
        choice = input("\nSelect email provider (1-3): ").strip()
        
        if choice == '1':
            self.config['EMAIL_PROVIDER'] = 'smtp'
            server = input("SMTP server (e.g., smtp.gmail.com): ").strip()
            port = input("SMTP port (default 587): ").strip() or '587'
            username = input("Email username: ").strip()
            password = input("Email password/app password: ").strip()
            
            if all([server, username, password]):
                self.config['MAIL_SERVER'] = server
                self.config['MAIL_PORT'] = port
                self.config['MAIL_USERNAME'] = username
                self.config['MAIL_PASSWORD'] = password
                self.config['MAIL_DEFAULT_SENDER'] = username
                print("✅ SMTP configured")
            else:
                print("❌ SMTP configuration incomplete")
        
        elif choice == '2':
            self.config['EMAIL_PROVIDER'] = 'webhook'
            webhook_url = input("Enter email webhook URL: ").strip()
            if webhook_url:
                self.config['EMAIL_WEBHOOK_URL'] = webhook_url
                print("✅ Email webhook configured")
            else:
                print("❌ Webhook URL required")
        
        elif choice == '3':
            self.config['EMAIL_PROVIDER'] = 'local'
            print("✅ Local email simulation configured")
        
        else:
            print("❌ Invalid choice")
    
    def configure_whatsapp(self):
        """Configure WhatsApp integration"""
        print("\n📱 WhatsApp Configuration")
        print("=" * 40)
        
        print("Available WhatsApp providers:")
        print("1. Z-API")
        print("2. Twilio")
        print("3. Webhook (Custom)")
        print("4. Local (Simulation)")
        
        choice = input("\nSelect WhatsApp provider (1-4): ").strip()
        
        if choice == '1':
            self.config['WHATSAPP_PROVIDER'] = 'z-api'
            api_key = input("Z-API token: ").strip()
            instance_id = input("Z-API instance ID: ").strip()
            
            if all([api_key, instance_id]):
                self.config['WHATSAPP_API_KEY'] = api_key
                self.config['WHATSAPP_INSTANCE_ID'] = instance_id
                print("✅ Z-API configured")
            else:
                print("❌ Z-API configuration incomplete")
        
        elif choice == '2':
            self.config['WHATSAPP_PROVIDER'] = 'twilio'
            account_sid = input("Twilio Account SID: ").strip()
            auth_token = input("Twilio Auth Token: ").strip()
            whatsapp_number = input("Twilio WhatsApp number: ").strip()
            
            if all([account_sid, auth_token, whatsapp_number]):
                self.config['WHATSAPP_API_KEY'] = account_sid
                self.config['TWILIO_AUTH_TOKEN'] = auth_token
                self.config['WHATSAPP_INSTANCE_ID'] = whatsapp_number
                print("✅ Twilio configured")
            else:
                print("❌ Twilio configuration incomplete")
        
        elif choice == '3':
            self.config['WHATSAPP_PROVIDER'] = 'webhook'
            webhook_url = input("Enter WhatsApp webhook URL: ").strip()
            if webhook_url:
                self.config['WHATSAPP_WEBHOOK_URL'] = webhook_url
                print("✅ WhatsApp webhook configured")
            else:
                print("❌ Webhook URL required")
        
        elif choice == '4':
            self.config['WHATSAPP_PROVIDER'] = 'local'
            print("✅ Local WhatsApp simulation configured")
        
        else:
            print("❌ Invalid choice")
    
    def configure_database(self):
        """Configure database"""
        print("\n🗄️ Database Configuration")
        print("=" * 40)
        
        print("Available database options:")
        print("1. SQLite (Development)")
        print("2. PostgreSQL (Production)")
        
        choice = input("\nSelect database (1-2): ").strip()
        
        if choice == '1':
            self.config['DATABASE_URL'] = 'sqlite:///pevapp22.db'
            self.config['DEV_DATABASE_URL'] = 'sqlite:///pevapp22_dev.db'
            print("✅ SQLite configured")
        
        elif choice == '2':
            host = input("PostgreSQL host (default localhost): ").strip() or 'localhost'
            port = input("PostgreSQL port (default 5432): ").strip() or '5432'
            database = input("Database name: ").strip()
            username = input("Username: ").strip()
            password = input("Password: ").strip()
            
            if all([database, username, password]):
                self.config['DATABASE_URL'] = f'postgresql://{username}:{password}@{host}:{port}/{database}'
                print("✅ PostgreSQL configured")
            else:
                print("❌ PostgreSQL configuration incomplete")
        
        else:
            print("❌ Invalid choice")
    
    def run(self):
        """Run configuration"""
        print("🚀 PEVAPP22 Integration Configuration")
        print("=" * 50)
        
        # Configure each service
        self.configure_database()
        self.configure_ai()
        self.configure_email()
        self.configure_whatsapp()
        
        # Save configuration
        print("\n💾 Saving configuration...")
        self.save_config()
        
        print("\n✅ Configuration completed!")
        print("\nNext steps:")
        print("1. Review .env file")
        print("2. Run: python setup.py")
        print("3. Run: python app_new.py")

if __name__ == "__main__":
    configurator = IntegrationConfigurator()
    configurator.run()
