from __future__ import annotations

from decimal import Decimal
from io import BytesIO
from typing import Iterable

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font

NFSE_INTEGRATION_HEADERS = ['CPF_CNPJ',
 'Nome',
 'Email',
 'Valor',
 'Codigo_Servico',
 'Endereco_Pais',
 'Endereco_Cep',
 'Endereco_Logradouro',
 'Endereco_Numero',
 'Endereco_Complemento',
 'Endereco_Bairro',
 'Endereco_Cidade_Codigo',
 'Endereco_Cidade_Nome',
 'Endereco_Estado',
 'Descricao',
 'Data_Competencia',
 'IBSCBS_Indicador_Operacao',
 'IBSCBS_Codigo_Classificacao',
 'IBSCBS_Tipo_Operacao',
 'IBSCBS_Uso_Pessoal',
 'NBS',
 'CNAE',
 'Regime_Tributario_Tomador',
 'Tipo_Tomador',
 'Informacoes_Adicionais',
 'Tipo_Tributacao',
 'Aliquota_ISS',
 'Valor_ISS',
 'Retencao_IR',
 'Retencao_PIS',
 'Retencao_COFINS',
 'Retencao_CSLL',
 'Retencao_INSS',
 'Retencao_ISS',
 'Retencao_OUTROS',
 'Valor_Deducoes',
 'Valor_Desconto_Incondicionado',
 'Valor_Desconto_Condicionado',
 'Valor_Recebido',
 'ID_Externo',
 'Pais_Prestacao_Servico',
 'Estado_Prestacao_Servico',
 'Cidade_Prestacao_Servico',
 'Codigo_Cidade_Prestacao_Servico',
 'Cep_Prestacao_Servico',
 'Logradouro_Prestacao_Servico',
 'Numero_Prestacao_Servico',
 'Bairro_Prestacao_Servico',
 'Complemento_Prestacao_Servico',
 'Nome_Atividade_Evento',
 'Data_Inicio_Evento',
 'Data_Fim_Evento',
 'Codigo_Atividade_Evento',
 'Evento_Endereco_Pais',
 'Evento_Endereco_Cep',
 'Evento_Endereco_Logradouro',
 'Evento_Endereco_Numero',
 'Evento_Endereco_Complemento',
 'Evento_Endereco_Bairro',
 'Evento_Endereco_Cidade_Codigo',
 'Evento_Endereco_Cidade_Nome',
 'Evento_Endereco_Estado',
 'Imovel_Inscricao_Fiscal',
 'Imovel_CIB',
 'Imovel_Endereco_Pais',
 'Imovel_Endereco_Cep',
 'Imovel_Endereco_Logradouro',
 'Imovel_Endereco_Numero',
 'Imovel_Endereco_Complemento',
 'Imovel_Endereco_Bairro',
 'Imovel_Endereco_Cidade_Codigo',
 'Imovel_Endereco_Cidade_Nome',
 'Imovel_Endereco_Estado',
 'Obra_CNO',
 'Obra_CEI',
 'Obra_CIB',
 'Obra_Endereco_Pais',
 'Obra_Endereco_Cep',
 'Obra_Endereco_Logradouro',
 'Obra_Endereco_Numero',
 'Obra_Endereco_Complemento',
 'Obra_Endereco_Bairro',
 'Obra_Endereco_Cidade_Codigo',
 'Obra_Endereco_Cidade_Nome',
 'Obra_Endereco_Estado',
 'Comercio_Exterior_Modo_Prestacao',
 'Comercio_Exterior_Vinculo',
 'Comercio_Exterior_Moeda',
 'Comercio_Exterior_Valor_Servico_Moeda',
 'Comercio_Exterior_Fomento_Prestador',
 'Comercio_Exterior_Fomento_Tomador',
 'Comercio_Exterior_Movimentacao_Temporaria_Bens',
 'Comercio_Exterior_Declaracao_Importacao',
 'Comercio_Exterior_Registro_Exportacao',
 'Comercio_Exterior_Envio_MDIC',
 'Intermediario_Tipo',
 'Intermediario_Nome',
 'Intermediario_CPF_CNPJ',
 'Intermediario_Inscricao_Municipal',
 'Intermediario_Inscricao_Estadual',
 'Intermediario_Regime_Tributario',
 'Intermediario_Telefone',
 'Intermediario_Email',
 'Intermediario_CAEPF',
 'Intermediario_Motivo_Sem_NIF',
 'Intermediario_Endereco_Pais',
 'Intermediario_Endereco_Cep',
 'Intermediario_Endereco_Logradouro',
 'Intermediario_Endereco_Numero',
 'Intermediario_Endereco_Complemento',
 'Intermediario_Endereco_Bairro',
 'Intermediario_Endereco_Cidade_Codigo',
 'Intermediario_Endereco_Cidade_Nome',
 'Intermediario_Endereco_Estado',
 'Destinatario_Nome',
 'Destinatario_CPF_CNPJ',
 'Destinatario_Email',
 'Destinatario_Endereco_Pais',
 'Destinatario_Endereco_Cep',
 'Destinatario_Endereco_Logradouro',
 'Destinatario_Endereco_Numero',
 'Destinatario_Endereco_Complemento',
 'Destinatario_Endereco_Bairro',
 'Destinatario_Endereco_Cidade_Codigo',
 'Destinatario_Endereco_Cidade_Nome',
 'Destinatario_Endereco_Estado',
 'Locacao_Categoria',
 'Locacao_Objeto',
 'Locacao_Extensao',
 'Locacao_Numero_Postes',
 'Beneficio_ID',
 'Beneficio_Valor',
 'Beneficio_Percentual',
 'Suspensao_Motivo',
 'Suspensao_Numero_Processo',
 'Tipo_Imunidade',
 'Tipo_Retencao',
 'Valor_Inicial_Cobrado',
 'Valor_Final_Cobrado',
 'Valor_Multa',
 'Valor_Juros',
 'IBSCBS_Codigo_Situacao',
 'IBSCBS_Finalidade',
 'IBSCBS_Indicador_Destino',
 'IBSCBS_Base_Calculo',
 'IBSCBS_Valor_Reembolso_Repasse',
 'IBSCBS_Valor_Deducao_Reducao',
 'IBSCBS_Doacao',
 'IBS_Estadual_Aliquota',
 'IBS_Estadual_Reducao_Aliquota',
 'IBS_Estadual_Aliquota_Efetiva',
 'IBS_Estadual_Valor',
 'IBS_Estadual_Diferimento_Percentual',
 'IBS_Estadual_Diferimento_Valor',
 'IBS_Estadual_Valor_Devolvido',
 'IBS_Municipal_Aliquota',
 'IBS_Municipal_Reducao_Aliquota',
 'IBS_Municipal_Aliquota_Efetiva',
 'IBS_Municipal_Valor',
 'IBS_Municipal_Diferimento_Percentual',
 'IBS_Municipal_Diferimento_Valor',
 'IBS_Municipal_Valor_Devolvido',
 'IBS_Total',
 'CBS_Aliquota',
 'CBS_Reducao_Aliquota',
 'CBS_Aliquota_Efetiva',
 'CBS_Valor',
 'CBS_Diferimento_Percentual',
 'CBS_Diferimento_Valor',
 'CBS_Valor_Devolvido',
 'CST_PIS_COFINS',
 'Base_Calculo_PIS_COFINS',
 'Aliquota_PIS',
 'Valor_PIS',
 'Aliquota_COFINS',
 'Valor_COFINS',
 'Aliquota_IR',
 'Aliquota_CSLL',
 'Aliquota_INSS',
 'Aliquota_IPI',
 'Valor_IPI',
 'NCM',
 'Pagamento_Parcelado_Antecipado',
 'CAEPF_Tomador',
 'Tomador_Motivo_Sem_NIF',
 'Info_Adicional_ART_RRT',
 'Info_Adicional_Documento_Referencia',
 'Info_Adicional_Pedido',
 'Info_Adicional_Itens_Pedido',
 'Info_Adicional_Outras_Informacoes',
 'Tributos_Aproximados_Fonte',
 'Tributos_Aproximados_Versao',
 'Tributos_Aproximados_Percentual_Total',
 'Tributos_Aproximados_Valor_Total',
 'Tributos_Aproximados_Federal_Percentual',
 'Tributos_Aproximados_Federal_Valor',
 'Tributos_Aproximados_Estadual_Percentual',
 'Tributos_Aproximados_Estadual_Valor',
 'Tributos_Aproximados_Municipal_Percentual',
 'Tributos_Aproximados_Municipal_Valor',
 'Tributos_Aproximados_Simples_Nacional',
 'Tributos_Aproximados_Total',
 'Tributos_Aproximados_Indicador',
 'Substituicao_Chave_NFSe',
 'Substituicao_Motivo',
 'Substituicao_Motivo_Texto']

NFSE_REFERENCE_FIELDS = ['CPF_CNPJ',
 'Nome',
 'Email',
 'Tomador_Telefone',
 'Tomador_Inscricao_Estadual',
 'Valor',
 'Codigo_Servico',
 'Endereco_Pais',
 'Endereco_Cep',
 'Endereco_Logradouro',
 'Endereco_Numero',
 'Endereco_Complemento',
 'Endereco_Bairro',
 'Endereco_Cidade_Codigo',
 'Endereco_Cidade_Nome',
 'Endereco_Estado',
 'Descricao',
 'Data_Competencia',
 'Serie_RPS',
 'Numero_RPS',
 'IBSCBS_Indicador_Operacao',
 'IBSCBS_Codigo_Classificacao',
 'IBSCBS_Tipo_Operacao',
 'IBSCBS_Uso_Pessoal',
 'NBS',
 'CNAE',
 'Regime_Tributario_Tomador',
 'Tipo_Tomador',
 'Informacoes_Adicionais',
 'Tipo_Tributacao',
 'Aliquota_ISS',
 'Valor_ISS',
 'Retencao_IR',
 'Retencao_PIS',
 'Retencao_COFINS',
 'Retencao_CSLL',
 'Retencao_INSS',
 'Retencao_ISS',
 'Retencao_OUTROS',
 'Valor_Deducoes',
 'Valor_Desconto_Incondicionado',
 'Valor_Desconto_Condicionado',
 'Valor_Recebido',
 'ID_Externo',
 'Pais_Prestacao_Servico',
 'Estado_Prestacao_Servico',
 'Cidade_Prestacao_Servico',
 'Codigo_Cidade_Prestacao_Servico',
 'Cep_Prestacao_Servico',
 'Logradouro_Prestacao_Servico',
 'Numero_Prestacao_Servico',
 'Bairro_Prestacao_Servico',
 'Complemento_Prestacao_Servico',
 'Nome_Atividade_Evento',
 'Data_Inicio_Evento',
 'Data_Fim_Evento',
 'Codigo_Atividade_Evento',
 'Evento_Endereco_Pais',
 'Evento_Endereco_Cep',
 'Evento_Endereco_Logradouro',
 'Evento_Endereco_Numero',
 'Evento_Endereco_Complemento',
 'Evento_Endereco_Bairro',
 'Evento_Endereco_Cidade_Codigo',
 'Evento_Endereco_Cidade_Nome',
 'Evento_Endereco_Estado',
 'Imovel_Inscricao_Fiscal',
 'Imovel_CIB',
 'Imovel_Endereco_Pais',
 'Imovel_Endereco_Cep',
 'Imovel_Endereco_Logradouro',
 'Imovel_Endereco_Numero',
 'Imovel_Endereco_Complemento',
 'Imovel_Endereco_Bairro',
 'Imovel_Endereco_Cidade_Codigo',
 'Imovel_Endereco_Cidade_Nome',
 'Imovel_Endereco_Estado',
 'Obra_CNO',
 'Obra_CEI',
 'Obra_CIB',
 'Obra_Endereco_Pais',
 'Obra_Endereco_Cep',
 'Obra_Endereco_Logradouro',
 'Obra_Endereco_Numero',
 'Obra_Endereco_Complemento',
 'Obra_Endereco_Bairro',
 'Obra_Endereco_Cidade_Codigo',
 'Obra_Endereco_Cidade_Nome',
 'Obra_Endereco_Estado',
 'Comercio_Exterior_Modo_Prestacao',
 'Comercio_Exterior_Vinculo',
 'Comercio_Exterior_Moeda',
 'Comercio_Exterior_Valor_Servico_Moeda',
 'Comercio_Exterior_Fomento_Prestador',
 'Comercio_Exterior_Fomento_Tomador',
 'Comercio_Exterior_Movimentacao_Temporaria_Bens',
 'Comercio_Exterior_Declaracao_Importacao',
 'Comercio_Exterior_Registro_Exportacao',
 'Comercio_Exterior_Envio_MDIC',
 'Intermediario_Tipo',
 'Intermediario_Nome',
 'Intermediario_CPF_CNPJ',
 'Intermediario_Inscricao_Municipal',
 'Intermediario_Inscricao_Estadual',
 'Intermediario_Regime_Tributario',
 'Intermediario_Telefone',
 'Intermediario_Email',
 'Intermediario_CAEPF',
 'Intermediario_Motivo_Sem_NIF',
 'Intermediario_Endereco_Pais',
 'Intermediario_Endereco_Cep',
 'Intermediario_Endereco_Logradouro',
 'Intermediario_Endereco_Numero',
 'Intermediario_Endereco_Complemento',
 'Intermediario_Endereco_Bairro',
 'Intermediario_Endereco_Cidade_Codigo',
 'Intermediario_Endereco_Cidade_Nome',
 'Intermediario_Endereco_Estado',
 'Destinatario_Nome',
 'Destinatario_CPF_CNPJ',
 'Destinatario_Email',
 'Destinatario_Endereco_Pais',
 'Destinatario_Endereco_Cep',
 'Destinatario_Endereco_Logradouro',
 'Destinatario_Endereco_Numero',
 'Destinatario_Endereco_Complemento',
 'Destinatario_Endereco_Bairro',
 'Destinatario_Endereco_Cidade_Codigo',
 'Destinatario_Endereco_Cidade_Nome',
 'Destinatario_Endereco_Estado',
 'Locacao_Categoria',
 'Locacao_Objeto',
 'Locacao_Extensao',
 'Locacao_Numero_Postes',
 'Beneficio_ID',
 'Beneficio_Valor',
 'Beneficio_Percentual',
 'Suspensao_Motivo',
 'Suspensao_Numero_Processo',
 'Tipo_Imunidade',
 'Tipo_Retencao',
 'Valor_Inicial_Cobrado',
 'Valor_Final_Cobrado',
 'Valor_Multa',
 'Valor_Juros',
 'IBSCBS_Codigo_Situacao',
 'IBSCBS_Finalidade',
 'IBSCBS_Indicador_Destino',
 'IBSCBS_Base_Calculo',
 'IBSCBS_Valor_Reembolso_Repasse',
 'IBSCBS_Valor_Deducao_Reducao',
 'IBSCBS_Doacao',
 'IBS_Estadual_Aliquota',
 'IBS_Estadual_Reducao_Aliquota',
 'IBS_Estadual_Aliquota_Efetiva',
 'IBS_Estadual_Valor',
 'IBS_Estadual_Diferimento_Percentual',
 'IBS_Estadual_Diferimento_Valor',
 'IBS_Estadual_Valor_Devolvido',
 'IBS_Municipal_Aliquota',
 'IBS_Municipal_Reducao_Aliquota',
 'IBS_Municipal_Aliquota_Efetiva',
 'IBS_Municipal_Valor',
 'IBS_Municipal_Diferimento_Percentual',
 'IBS_Municipal_Diferimento_Valor',
 'IBS_Municipal_Valor_Devolvido',
 'IBS_Total',
 'CBS_Aliquota',
 'CBS_Reducao_Aliquota',
 'CBS_Aliquota_Efetiva',
 'CBS_Valor',
 'CBS_Diferimento_Percentual',
 'CBS_Diferimento_Valor',
 'CBS_Valor_Devolvido',
 'CST_PIS_COFINS',
 'Base_Calculo_PIS_COFINS',
 'Aliquota_PIS',
 'Valor_PIS',
 'Aliquota_COFINS',
 'Valor_COFINS',
 'Aliquota_IR',
 'Aliquota_CSLL',
 'Aliquota_INSS',
 'Aliquota_IPI',
 'Valor_IPI',
 'NCM',
 'Pagamento_Parcelado_Antecipado',
 'CAEPF_Tomador',
 'Tomador_Motivo_Sem_NIF',
 'Info_Adicional_ART_RRT',
 'Info_Adicional_Documento_Referencia',
 'Info_Adicional_Pedido',
 'Info_Adicional_Itens_Pedido',
 'Info_Adicional_Outras_Informacoes',
 'Tributos_Aproximados_Fonte',
 'Tributos_Aproximados_Versao',
 'Tributos_Aproximados_Percentual_Total',
 'Tributos_Aproximados_Valor_Total',
 'Tributos_Aproximados_Federal_Percentual',
 'Tributos_Aproximados_Federal_Valor',
 'Tributos_Aproximados_Estadual_Percentual',
 'Tributos_Aproximados_Estadual_Valor',
 'Tributos_Aproximados_Municipal_Percentual',
 'Tributos_Aproximados_Municipal_Valor',
 'Tributos_Aproximados_Simples_Nacional',
 'Tributos_Aproximados_Total',
 'Tributos_Aproximados_Indicador',
 'Substituicao_Chave_NFSe',
 'Substituicao_Motivo',
 'Substituicao_Motivo_Texto']

NFSE_FILLED_SAMPLE_HEADERS = ['CPF_CNPJ',
 'Nome',
 'Email',
 'Valor',
 'Codigo_Servico',
 'Endereco_Pais',
 'Endereco_Cep',
 'Endereco_Logradouro',
 'Endereco_Numero',
 'Endereco_Bairro',
 'Endereco_Cidade_Codigo',
 'Endereco_Cidade_Nome',
 'Endereco_Estado',
 'Descricao',
 'IBSCBS_Indicador_Operacao',
 'IBSCBS_Codigo_Classificacao',
 'IBSCBS_Tipo_Operacao',
 'NBS',
 'CNAE',
 'Aliquota_ISS',
 'Valor_ISS',
 'Retencao_OUTROS']

NFSE_REQUIRED_HEADERS = set(['CPF_CNPJ',
 'Nome',
 'Valor',
 'Codigo_Servico',
 'Endereco_Pais',
 'Endereco_Cep',
 'Endereco_Logradouro',
 'Endereco_Numero',
 'Endereco_Bairro',
 'Endereco_Cidade_Codigo',
 'Endereco_Cidade_Nome',
 'Endereco_Estado',
 'Descricao'])

NFSE_HEADER_WIDTHS = {'Aliquota_COFINS': 16.22,
 'Aliquota_CSLL': 13.55,
 'Aliquota_INSS': 13.78,
 'Aliquota_IPI': 11.78,
 'Aliquota_IR': 11.22,
 'Aliquota_ISS': 12.22,
 'Aliquota_PIS': 12.22,
 'Bairro_Prestacao_Servico': 23.78,
 'Base_Calculo_PIS_COFINS': 24.22,
 'Beneficio_ID': 12.22,
 'Beneficio_Percentual': 20.22,
 'Beneficio_Valor': 15.22,
 'CAEPF_Tomador': 15.55,
 'CBS_Aliquota': 12.78,
 'CBS_Aliquota_Efetiva': 20.22,
 'CBS_Diferimento_Percentual': 27.22,
 'CBS_Diferimento_Valor': 22.22,
 'CBS_Reducao_Aliquota': 21.78,
 'CBS_Valor': 10.0,
 'CBS_Valor_Devolvido': 20.22,
 'CNAE': 7.78,
 'CPF_CNPJ': 17.78,
 'CST_PIS_COFINS': 15.55,
 'Cep_Prestacao_Servico': 21.78,
 'Cidade_Prestacao_Servico': 24.55,
 'Codigo_Atividade_Evento': 24.22,
 'Codigo_Cidade_Prestacao_Servico': 32.0,
 'Codigo_Servico': 19.22,
 'Comercio_Exterior_Declaracao_Importacao': 40.0,
 'Comercio_Exterior_Envio_MDIC': 29.78,
 'Comercio_Exterior_Fomento_Prestador': 36.78,
 'Comercio_Exterior_Fomento_Tomador': 36.22,
 'Comercio_Exterior_Modo_Prestacao': 34.22,
 'Comercio_Exterior_Moeda': 25.22,
 'Comercio_Exterior_Movimentacao_Temporaria_Bens': 49.44,
 'Comercio_Exterior_Registro_Exportacao': 37.22,
 'Comercio_Exterior_Valor_Servico_Moeda': 38.78,
 'Comercio_Exterior_Vinculo': 25.78,
 'Complemento_Prestacao_Servico': 31.44,
 'Data_Competencia': 18.0,
 'Data_Fim_Evento': 16.55,
 'Data_Inicio_Evento': 18.22,
 'Descricao': 42.78,
 'Destinatario_CPF_CNPJ': 22.0,
 'Destinatario_Email': 18.0,
 'Destinatario_Endereco_Bairro': 28.0,
 'Destinatario_Endereco_Cep': 13.0,
 'Destinatario_Endereco_Cidade_Codigo': 36.22,
 'Destinatario_Endereco_Cidade_Nome': 35.55,
 'Destinatario_Endereco_Complemento': 35.78,
 'Destinatario_Endereco_Estado': 28.55,
 'Destinatario_Endereco_Logradouro': 32.78,
 'Destinatario_Endereco_Numero': 30.22,
 'Destinatario_Endereco_Pais': 26.22,
 'Destinatario_Nome': 18.55,
 'Email': 24.11,
 'Endereco_Bairro': 15.78,
 'Endereco_Cep': 13.78,
 'Endereco_Cidade_Codigo': 24.0,
 'Endereco_Cidade_Nome': 23.22,
 'Endereco_Complemento': 23.44,
 'Endereco_Estado': 16.22,
 'Endereco_Logradouro': 31.55,
 'Endereco_Numero': 17.78,
 'Endereco_Pais': 14.0,
 'Estado_Prestacao_Servico': 24.22,
 'Evento_Endereco_Bairro': 23.22,
 'Evento_Endereco_Cep': 21.22,
 'Evento_Endereco_Cidade_Codigo': 31.44,
 'Evento_Endereco_Cidade_Nome': 30.78,
 'Evento_Endereco_Complemento': 30.78,
 'Evento_Endereco_Estado': 23.78,
 'Evento_Endereco_Logradouro': 28.0,
 'Evento_Endereco_Numero': 25.22,
 'Evento_Endereco_Pais': 21.44,
 'IBSCBS_Base_Calculo': 19.78,
 'IBSCBS_Codigo_Classificacao': 26.78,
 'IBSCBS_Codigo_Situacao': 23.0,
 'IBSCBS_Doacao': 14.78,
 'IBSCBS_Finalidade': 17.55,
 'IBSCBS_Indicador_Destino': 24.55,
 'IBSCBS_Indicador_Operacao': 26.22,
 'IBSCBS_Tipo_Operacao': 21.78,
 'IBSCBS_Uso_Pessoal': 19.44,
 'IBSCBS_Valor_Deducao_Reducao': 30.78,
 'IBSCBS_Valor_Reembolso_Repasse': 32.78,
 'IBS_Estadual_Aliquota': 21.0,
 'IBS_Estadual_Aliquota_Efetiva': 28.44,
 'IBS_Estadual_Diferimento_Percentual': 35.44,
 'IBS_Estadual_Diferimento_Valor': 30.44,
 'IBS_Estadual_Reducao_Aliquota': 30.0,
 'IBS_Estadual_Valor': 18.22,
 'IBS_Estadual_Valor_Devolvido': 28.44,
 'IBS_Municipal_Aliquota': 22.55,
 'IBS_Municipal_Aliquota_Efetiva': 30.0,
 'IBS_Municipal_Diferimento_Percentual': 36.78,
 'IBS_Municipal_Diferimento_Valor': 31.78,
 'IBS_Municipal_Reducao_Aliquota': 31.44,
 'IBS_Municipal_Valor': 19.55,
 'IBS_Municipal_Valor_Devolvido': 30.0,
 'IBS_Total': 9.22,
 'ID_Externo': 10.78,
 'Imovel_CIB': 11.0,
 'Imovel_Endereco_Bairro': 23.22,
 'Imovel_Endereco_Cep': 21.22,
 'Imovel_Endereco_Cidade_Codigo': 31.44,
 'Imovel_Endereco_Cidade_Nome': 30.78,
 'Imovel_Endereco_Complemento': 30.78,
 'Imovel_Endereco_Estado': 23.78,
 'Imovel_Endereco_Logradouro': 28.0,
 'Imovel_Endereco_Numero': 25.22,
 'Imovel_Endereco_Pais': 21.44,
 'Imovel_Inscricao_Fiscal': 22.22,
 'Info_Adicional_ART_RRT': 23.0,
 'Info_Adicional_Documento_Referencia': 36.55,
 'Info_Adicional_Itens_Pedido': 27.22,
 'Info_Adicional_Outras_Informacoes': 33.44,
 'Info_Adicional_Pedido': 21.55,
 'Informacoes_Adicionais': 22.55,
 'Intermediario_CAEPF': 20.22,
 'Intermediario_CPF_CNPJ': 23.44,
 'Intermediario_Email': 19.44,
 'Intermediario_Endereco_Bairro': 29.44,
 'Intermediario_Endereco_Cep': 27.55,
 'Intermediario_Endereco_Cidade_Codigo': 37.78,
 'Intermediario_Endereco_Cidade_Nome': 37.0,
 'Intermediario_Endereco_Complemento': 37.22,
 'Intermediario_Endereco_Estado': 30.22,
 'Intermediario_Endereco_Logradouro': 34.44,
 'Intermediario_Endereco_Numero': 31.55,
 'Intermediario_Endereco_Pais': 27.78,
 'Intermediario_Inscricao_Estadual': 31.22,
 'Intermediario_Inscricao_Municipal': 32.55,
 'Intermediario_Motivo_Sem_NIF': 30.22,
 'Intermediario_Nome': 20.0,
 'Intermediario_Regime_Tributario': 31.44,
 'Intermediario_Telefone': 22.78,
 'Intermediario_Tipo': 18.44,
 'Locacao_Categoria': 17.55,
 'Locacao_Extensao': 17.0,
 'Locacao_Numero_Postes': 23.44,
 'Locacao_Objeto': 15.22,
 'Logradouro_Prestacao_Servico': 28.55,
 'NBS': 4.55,
 'NCM': 5.44,
 'Nome': 32.78,
 'Nome_Atividade_Evento': 23.55,
 'Numero_Prestacao_Servico': 25.78,
 'Obra_CEI': 9.0,
 'Obra_CIB': 9.22,
 'Obra_CNO': 10.22,
 'Obra_Endereco_Bairro': 21.22,
 'Obra_Endereco_Cep': 19.22,
 'Obra_Endereco_Cidade_Codigo': 29.44,
 'Obra_Endereco_Cidade_Nome': 28.78,
 'Obra_Endereco_Complemento': 28.78,
 'Obra_Endereco_Estado': 21.78,
 'Obra_Endereco_Logradouro': 26.22,
 'Obra_Endereco_Numero': 23.22,
 'Obra_Endereco_Pais': 19.44,
 'Pagamento_Parcelado_Antecipado': 32.55,
 'Pais_Prestacao_Servico': 22.0,
 'Regime_Tributario_Tomador': 26.78,
 'Retencao_COFINS': 17.0,
 'Retencao_CSLL': 14.22,
 'Retencao_INSS': 14.44,
 'Retencao_IR': 12.0,
 'Retencao_ISS': 12.78,
 'Retencao_OUTROS': 18.0,
 'Retencao_PIS': 13.22,
 'Substituicao_Chave_NFSe': 24.22,
 'Substituicao_Motivo': 19.55,
 'Substituicao_Motivo_Texto': 25.78,
 'Suspensao_Motivo': 18.22,
 'Suspensao_Numero_Processo': 28.22,
 'Tipo_Imunidade': 15.55,
 'Tipo_Retencao': 14.22,
 'Tipo_Tomador': 13.78,
 'Tipo_Tributacao': 15.22,
 'Tomador_Motivo_Sem_NIF': 25.78,
 'Tributos_Aproximados_Estadual_Percentual': 41.0,
 'Tributos_Aproximados_Estadual_Valor': 36.0,
 'Tributos_Aproximados_Federal_Percentual': 40.22,
 'Tributos_Aproximados_Federal_Valor': 35.22,
 'Tributos_Aproximados_Fonte': 27.78,
 'Tributos_Aproximados_Indicador': 31.0,
 'Tributos_Aproximados_Municipal_Percentual': 42.55,
 'Tributos_Aproximados_Municipal_Valor': 37.44,
 'Tributos_Aproximados_Percentual_Total': 38.0,
 'Tributos_Aproximados_Simples_Nacional': 38.78,
 'Tributos_Aproximados_Total': 27.0,
 'Tributos_Aproximados_Valor_Total': 32.78,
 'Tributos_Aproximados_Versao': 28.78,
 'Valor': 9.78,
 'Valor_COFINS': 13.44,
 'Valor_Deducoes': 15.55,
 'Valor_Desconto_Condicionado': 28.78,
 'Valor_Desconto_Incondicionado': 30.22,
 'Valor_Final_Cobrado': 19.78,
 'Valor_IPI': 9.0,
 'Valor_ISS': 9.22,
 'Valor_Inicial_Cobrado': 20.78,
 'Valor_Juros': 11.22,
 'Valor_Multa': 12.0,
 'Valor_PIS': 9.44,
 'Valor_Recebido': 15.22}

NFSE_XLSX_MIMETYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

_TEXT_HEADERS = set(NFSE_INTEGRATION_HEADERS) - {"Valor"}


def _normalize_cell_value(header: str, value):
    if value in (None, ""):
        return None
    if header == "Valor":
        if isinstance(value, Decimal):
            return float(value)
        return value
    return str(value)


def build_nfse_integration_workbook(rows: Iterable[dict]) -> bytes:
    """Gera XLSX no layout da planilha avançada de integração NFS-e usada pela Save Water."""
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Sheet1"

    for col_index, header in enumerate(NFSE_INTEGRATION_HEADERS, start=1):
        cell = sheet.cell(row=1, column=col_index, value=header)
        color = "EC4040" if header in NFSE_REQUIRED_HEADERS else "44546A"
        cell.font = Font(bold=True, color=color)
        cell.alignment = Alignment(horizontal="center")
        sheet.column_dimensions[cell.column_letter].width = NFSE_HEADER_WIDTHS.get(header, 14)

    for row_index, row in enumerate(rows, start=2):
        for col_index, header in enumerate(NFSE_INTEGRATION_HEADERS, start=1):
            value = _normalize_cell_value(header, row.get(header))
            cell = sheet.cell(row=row_index, column=col_index, value=value)
            if header in _TEXT_HEADERS:
                cell.number_format = "@"

    reference_sheet = workbook.create_sheet("Sheet2")
    reference_sheet.column_dimensions["A"].width = 38
    for row_index, field_name in enumerate(NFSE_REFERENCE_FIELDS, start=1):
        reference_sheet.cell(row=row_index, column=1, value=field_name)

    output = BytesIO()
    workbook.save(output)
    return output.getvalue()
