from scripts.deploy.configr_remote_helper import connect_ssh, run_command, APP_DIR, BASE_DIR
ssh = connect_ssh()
cmd = (
    f"bash -lc \"source '{BASE_DIR}/activate' && cd '{APP_DIR}' && python - <<'PY'\n"
    "from app import create_app\n"
    "from models import User, Employee, Company, Meeting\n"
    "app = create_app()\n"
    "with app.app_context():\n"
    "    admin = User.query.filter(User.role.in_(['admin', 'administrator'])).order_by(User.id.asc()).first()\n"
    "    if not admin:\n"
    "        admin = User.query.order_by(User.id.asc()).first()\n"
    "    employee = Employee.query.filter_by(user_id=admin.id, status='active').order_by(Employee.id.asc()).first() if admin else None\n"
    "    first_company = Company.query.order_by(Company.id.asc()).first()\n"
    "    company_id = employee.company_id if employee else (first_company.id if first_company else 1)\n"
    "    meeting = Meeting.query.filter_by(company_id=company_id).order_by(Meeting.id.asc()).first()\n"
    "    tests = [\n"
    "      ('POST_AGENT_MENU_INVALID', 'POST', '/api/agents/menu/options', {}),\n"
    "      ('GET_AGENT_APPROVALS', 'GET', '/api/agents/actions/workflow-approvals/board', None),\n"
    "      ('GET_AGENT_USAGE', 'GET', '/api/agents/workflow-usage/metrics', None),\n"
    "      ('GET_AGENT_CATALOG', 'GET', '/api/agents/workflows/catalog', None),\n"
    "    ]\n"
    "    if meeting:\n"
    "        tests.extend([\n"
    "          ('GET_MEETING_API', 'GET', '/meetings/api/meeting/{}'.format(meeting.id), None),\n"
    "          ('GET_MEETING_ACTIVITIES', 'GET', '/meetings/api/meeting/{}/atividades'.format(meeting.id), None),\n"
    "          ('POST_MEETING_SYNC', 'POST', '/meetings/api/meeting/{}/sync-activities'.format(meeting.id), None),\n"
    "          ('POST_MEETING_START', 'POST', '/meetings/api/meeting/{}/iniciar'.format(meeting.id), None),\n"
    "          ('POST_MEETING_PRELIM', 'POST', '/meetings/api/meeting/{}/preliminares'.format(meeting.id), {'summary': ''}),\n"
    "        ])\n"
    "    with app.test_client() as client:\n"
    "        if admin:\n"
    "            client.post('/login', json={'email': admin.email, 'password': '123456'})\n"
    "            client.post('/portal', json={'company_id': company_id})\n"
    "        for label, method, path, payload in tests:\n"
    "            try:\n"
    "                if method == 'GET':\n"
    "                    resp = client.get(path, follow_redirects=False)\n"
    "                else:\n"
    "                    resp = client.post(path, json=payload) if payload is not None else client.post(path)\n"
    "                print('API::{}::{}::{}'.format(label, resp.status_code, path))\n"
    "                if resp.status_code >= 500:\n"
    "                    print(resp.get_data(as_text=True)[:1500])\n"
    "            except Exception as exc:\n"
    "                print('API::{}::EXC::{}'.format(label, exc))\n"
    "PY\""
)
code, out, err = run_command(ssh, cmd)
print('CODE:', code)
if out: print('OUT:\n' + out)
if err: print('ERR:\n' + err)
ssh.close()
