from scripts.deploy.configr_remote_helper import connect_ssh, run_command, APP_DIR, BASE_DIR
ssh = connect_ssh()
cmd = (
    f"bash -lc \"source '{BASE_DIR}/activate' && cd '{APP_DIR}' && python - <<'PY'\n"
    "from app import create_app\n"
    "from models import User, Employee, Company, Meeting\n"
    "app = create_app()\n"
    "with app.app_context():\n"
    "    admin = User.query.filter(User.role.in_(['admin', 'administrator'])).order_by(User.id.asc()).first()\n"
    "    if not admin:\n"
    "        admin = User.query.order_by(User.id.asc()).first()\n"
    "    employee = Employee.query.filter_by(user_id=admin.id, status='active').order_by(Employee.id.asc()).first() if admin else None\n"
    "    company_id = employee.company_id if employee else 9\n"
    "    meeting = Meeting.query.filter_by(company_id=company_id, id=1).first() or Meeting.query.filter_by(company_id=company_id).order_by(Meeting.id.asc()).first()\n"
    "    if not meeting:\n"
    "        print('NO_MEETING')\n"
    "    else:\n"
    "        payload_pre = {\n"
    "            'company_id': meeting.company_id,\n"
    "            'title': meeting.title,\n"
    "            'scheduled_date': meeting.scheduled_date.isoformat() if meeting.scheduled_date else None,\n"
    "            'scheduled_time': meeting.scheduled_time,\n"
    "            'planned_duration_minutes': meeting.planned_duration_minutes,\n"
    "            'invite_notes': meeting.invite_notes,\n"
    "            'guests': meeting.to_dict().get('guests') or {},\n"
    "            'agenda': meeting.to_dict().get('agenda') or [],\n"
    "        }\n"
    "        payload_exec = {\n"
    "            'company_id': meeting.company_id,\n"
    "            'meeting_notes': meeting.meeting_notes or '',\n"
    "            'participants': meeting.to_dict().get('participants') or {'internal': [], 'external': []},\n"
    "            'discussions': meeting.to_dict().get('discussions') or [],\n"
    "            'activities': meeting.to_dict().get('activities') or [],\n"
    "            'actual_duration_minutes': meeting.actual_duration_minutes,\n"
    "        }\n"
    "        tests = [\n"
    "            ('PUT_PRELIM_OK', 'PUT', f'/meetings/api/meeting/{meeting.id}', payload_pre),\n"
    "            ('PUT_EXEC_OK', 'PUT', f'/meetings/api/meeting/{meeting.id}/execucao', payload_exec),\n"
    "            ('GET_SYNC_CHECK', 'GET', f'/meetings/api/meeting/{meeting.id}/check-sync', None),\n"
    "            ('POST_SYNC_JSON', 'POST', f'/meetings/api/meeting/{meeting.id}/sync-activities', {'company_id': meeting.company_id, 'activities': []}),\n"
    "        ]\n"
    "        with app.test_client() as client:\n"
    "            client.post('/login', json={'email': admin.email, 'password': '123456'})\n"
    "            client.post('/portal', json={'company_id': meeting.company_id})\n"
    "            for label, method, path, payload in tests:\n"
    "                if method == 'GET':\n"
    "                    resp = client.get(path, follow_redirects=False)\n"
    "                elif method == 'PUT':\n"
    "                    resp = client.put(path, json=payload)\n"
    "                else:\n"
    "                    resp = client.post(path, json=payload)\n"
    "                print('TEST::{}::{}::{}'.format(label, resp.status_code, path))\n"
    "                print((resp.get_data(as_text=True) or '')[:500])\n"
    "PY\""
)
code, out, err = run_command(ssh, cmd)
print('CODE:', code)
if out: print('OUT:\n' + out)
if err: print('ERR:\n' + err)
ssh.close()
