[uwsgi]
## Flask Override
pythonpath = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/www/app32
module = passenger_wsgi:application
logto = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/www/uwsgi_app.log
daemonize = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/www/uwsgi_app.log
