#!/usr/bin/env python3
"""
Script para configurar a API Key da OpenAI
"""

import os

def configure_openai_key():
    """Configura a API Key da OpenAI no arquivo .env"""
    
    print("🔧 Configurando API Key da OpenAI...")
    
    # Sua chave (você precisa fornecer a chave completa)
    api_key = input("Digite sua API Key completa da OpenAI (sk-proj-...): ").strip()
    
    if not api_key.startswith('sk-'):
        print("❌ Formato de API Key inválido. Deve começar com 'sk-'")
        return False
    
    # Conteúdo do arquivo .env
    env_content = f"""# APP25 Configuration
# Generated by integrations page

# Database
DATABASE_URL=sqlite:///pevapp22.db
DEV_DATABASE_URL=sqlite:///pevapp22_dev.db

# Security
SECRET_KEY=dev-secret-key-change-in-production
LOGIN_DISABLED=False

# Email Configuration
MAIL_SERVER=
MAIL_PORT=587
MAIL_USE_TLS=True
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_DEFAULT_SENDER=

# AI Integration
AI_PROVIDER=openai
AI_API_KEY={api_key}
AI_WEBHOOK_URL=

# WhatsApp Integration
WHATSAPP_PROVIDER=disabled
WHATSAPP_API_KEY=
WHATSAPP_WEBHOOK_URL=

# File Uploads
UPLOAD_FOLDER=uploads
PDF_TEMP_FOLDER=temp_pdfs

# Redis
REDIS_URL=redis://localhost:6379/0

# Environment
FLASK_ENV=development"""
    
    try:
        # Salvar arquivo .env
        with open('.env', 'w', encoding='utf-8') as f:
            f.write(env_content)
        
        print("✅ Arquivo .env criado com sucesso!")
        print(f"✅ API Key configurada: {api_key[:10]}...")
        print("✅ Provedor: OpenAI")
        
        return True
        
    except Exception as e:
        print(f"❌ Erro ao criar arquivo .env: {e}")
        return False

def test_configuration():
    """Testa a configuração"""
    print("\n🧪 Testando configuração...")
    
    try:
        from dotenv import load_dotenv
        load_dotenv()
        
        provider = os.environ.get('AI_PROVIDER', 'não definido')
        api_key = os.environ.get('AI_API_KEY', 'não definida')
        
        print(f"✅ Provedor: {provider}")
        print(f"✅ API Key: {api_key[:10]}..." if api_key != 'não definida' else "❌ API Key não encontrada")
        
        if provider == 'openai' and api_key.startswith('sk-'):
            print("🎉 Configuração válida!")
            return True
        else:
            print("❌ Configuração inválida")
            return False
            
    except Exception as e:
        print(f"❌ Erro ao testar: {e}")
        return False

if __name__ == '__main__':
    print("🚀 Configurador de API Key da OpenAI")
    print("=" * 40)
    
    if configure_openai_key():
        test_configuration()
        
        print("\n📋 Próximos passos:")
        print("1. Execute: python app_pev.py")
        print("2. Acesse: http://localhost:5000/dashboard")
        print("3. Vá para 'Status dos Serviços'")
        print("4. Verifique se a IA está 'Ativo'")
        print("5. Teste executando um agente")
    else:
        print("\n❌ Configuração falhou. Tente novamente.")
