[uwsgi]
chdir           = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/www
pythonpath      = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/.virtualenv/3.12/lib/python3.12/site-packages
pythonpath      = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/www/app32

module          = passenger_wsgi:application
env             = 
logto           = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/log/uwsgi/uwsgi.log
daemonize       = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/log/uwsgi/uwsgi.log
harakiri        = 300

no-site         = true
master          = true
workers         = 1
enable-threads  = true
lazy-apps       = true
uid             = app
gid             = www-data
chmod-socket    = 664
socket          = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/etc/uwsgi/app.sock
stats           = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/etc/uwsgi/stats
vacuum          = true

buffer-size     = 12288

## LOAD ENVIROMENT VARIABLES IN .env FILE
for-readline    = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/www/app32/.env
  env = %(_)
endfor = 

## LOAD ALL OTHERS CONFIGURATION 
for-readline    = /srv/appgestaoversuscombr.45a4cd4b.configr.cloud/etc/uwsgi/conf.d/*.ini
  %(_)
endfor = 
